# Default configuration file for SCAMP 2.10.0
# EB 2020-12-01
#
 
#---------------------------- Reference catalogs ------------------------------
 
REF_SERVER         vizier.unistra.fr   # Internet addresses of catalog servers
                                       # Possible mirrors include:
                                       # vizier.nao.ac.jp,
                                       # vizier.hia.nrc.ca,
                                       # vizier.ast.cam.ac.uk,
                                       # vizier.iucaa.in,
                                       # vizier.china-vo.org,
                                       # vizier.cfa.harvard.edu and
                                       # viziersaao.chpc.ac.za
ASTREF_CATALOG         GAIA-EDR3          # NONE,FILE,USNO-A2,USNO-B1,GSC-2.3,
                                       # TYCHO-2,UCAC-4,URAT-1,NOMAD-1,PPMX,
                                       # CMC-15,2MASS,DENIS-3,SDSS-R9,SDSS-R12,
                                       # IGSL,GAIA-DR1,GAIA-DR2,GAIA-EDR3,
                                       # PANSTARRS-1, or ALLWISE
ASTREF_BAND            G         # Photom. band for astr.ref.magnitudes
 
#---------------------------- Cross-identification ----------------------------
 
CROSSID_RADIUS         2.0             # Cross-id initial radius (arcsec)
 
#---------------------------- Astrometric solution ----------------------------
 
SOLVE_ASTROM           Y               # Compute astrometric solution (Y/N) ?
PROJECTION_TYPE        SAME            # SAME, TPV or TAN
ASTRINSTRU_KEY         FILTER,QRUNID   # FITS keyword(s) defining the astrom
STABILITY_TYPE         INSTRUMENT      # EXPOSURE, PRE-DISTORTED or INSTRUMENT
CENTROID_KEYS          XWIN_IMAGE,YWIN_IMAGE # Cat. parameters for centroiding
CENTROIDERR_KEYS       ERRAWIN_IMAGE,ERRBWIN_IMAGE,ERRTHETAWIN_IMAGE
                                       # Cat. params for centroid err ellipse
DISTORT_KEYS           XWIN_IMAGE,YWIN_IMAGE # Cat. parameters or FITS keywords
DISTORT_GROUPS         1,1             # Polynom group for each context key
CHECKPLOT_TYPE         DISTORTION
CHECKPLOT_NAME         distort.png      # Check-plot filename for astrometric solution
DISTORT_DEGREES        4               # Polynom degree for each group
 
#---------------------------- Photometric solution ----------------------------
 
SOLVE_PHOTOM           N               # Compute photometric solution (Y/N) ?
 
#------------------------------- Check-plots ----------------------------------
 
CHECKPLOT_DEV          PNG             # NULL, XWIN, TK, PS, PSC, XFIG, PNG,
                                       # JPEG, AQT, PDF or SVG
 
#------------------------------ Miscellaneous ---------------------------------
 
VERBOSE_TYPE           NORMAL          # QUIET, NORMAL, LOG or FULL
WRITE_XML              N               # Write XML file (Y/N)?