# ============================================================
# REFERENCE CATALOG
# ============================================================

ASTREF_CATALOG     GAIA-EDR3
ASTREF_BAND        G

ASTRINSTRU_KEY     FILTER

# ============================================================
# MATCHING (SCAMP 2.10 REAL KEYS)
# ============================================================

#MATCH              Y
#MATCH_NMAX         1

# ============================================================
# DISTORTION MODEL
# ============================================================

DISTORT_DEGREES    4

# ============================================================
# OUTPUT
# ============================================================

#VERBOSE_TYPE       NORMAL

CHECKPLOT_TYPE     NONE